# Dockerfile para Laravel
FROM php:8.2-fpm

# Instalar dependências do sistema
RUN apt-get update && apt-get install -y \
    git \
    curl \
    libpng-dev \
    libjpeg-dev \
    libfreetype6-dev \
    zip \
    unzip

# Instalar extensões do PHP
RUN docker-php-ext-install pdo pdo_mysql gd

# Instalar Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

WORKDIR /var/www

COPY . .

RUN composer install

#COPY .env.example .env

RUN php artisan key:generate
RUN php artisan migrate
RUN php artisan serve --host=0.0.0.0 --port=8000

EXPOSE 8000

CMD ["php-fpm"]
