version: '3'
services:
  laravel-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - mysql-db
    networks:
      - laravel-net
    command: sh -c "php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=8000"
  
  vue-app:
    build:
      context: ./teste-dev-front-vue
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./teste-dev-front-vue:/app
    depends_on:
      - laravel-app
    networks:
      - laravel-net
  
  mysql-db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: your_mysql_root_password
    networks:
      - laravel-net

networks:
  laravel-net:
    driver: bridge
